server:
  port: 8083 # 所有后端请求的入口
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.alibaba.nacos.client: INFO
    com.alibaba.nacos.client.naming: WARN
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
spring:
  application:
    name: api-gateway-fyb
  config:
    import: optional:nacos:shared-config.yml
      # 引入共享配置
      # - "nacos:shared-config.yml"
  cloud:
    nacos:
      server-addr: 3.113.113.164:8848
      username: nacos
      password: passw0rd
      config:
        # 明确告诉 Nacos Config 默认的文件扩展名是 yml
        file-extension: yml
        group: DEFAULT_GROUP
    gateway:
      discovery:
        locator:
          enabled: false # 开启基于服务发现的路由功能
          lower-case-service-id: true # 将服务名转为小写路径，e.g., user-service -> /user-service/**
      routes:
        - id: user_service_route
          uri: lb://user-service-fyb
          predicates:
            - Path=/api/gateway/user/**
          filters:
            - StripPrefix=2
        - id: qa_service_route
          uri: lb://qa-service-fyb
          predicates:
            - Path=/api/gateway/qa/**
          filters:
            - StripPrefix=2
      default-filters:
        # 配置默认的限流过滤器
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@ipKeyResolver}'
services:
  qa:
    base-url: ${QA_SERVICE_BASE_URL:http://qa-service-fyb}