version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: ai-qa-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ai_qa_system}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ai_qa_system}
      MYSQL_USER: ${MYSQL_USER:-ai_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ai_user_pass}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend-services/user-service/src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  user-service:
    image: ${DOCKERHUB_USERNAME}/ai-qa-user-service:latest
    container_name: ai-qa-user-service
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ai_qa_system}
      MYSQL_USER: ${MYSQL_USER:-ai_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ai_user_pass}
      NACOS_SERVER_ADDR: ${NACOS_SERVER_ADDR}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8081"

  qa-service:
    image: ${DOCKERHUB_USERNAME:-youruser}/ai-qa-qa-service:latest
    container_name: ai-qa-qa-service
    depends_on:
      - mysql
    environment:
      NACOS_SERVER_ADDR: ${NACOS_SERVER_ADDR}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8082:8082"

  api-gateway:
    image: ${DOCKERHUB_USERNAME:-youruser}/ai-qa-api-gateway:latest
    container_name: ai-qa-api-gateway
    depends_on:
      - user-service
      - qa-service
    environment:
      NACOS_SERVER_ADDR: ${NACOS_SERVER_ADDR}
      SECURITY_JWT_SECRET: ${JWT_SECRET}
      SECURITY_JWT_ISSUER: user-service-fyb
    ports:
      - "8083:8083"

  # frontend:
  #   image: ${DOCKERHUB_USERNAME:-youruser}/ai-qa-frontend:latest
  #   container_name: ai-qa-frontend
  #   depends_on:
  #     - api-gateway
  #   environment:
  #     NEXT_PUBLIC_API_BASE_URL: ${FRONTEND_API_BASE_URL:-http://api-gateway:8083}
  #     NODE_ENV: production
  #   ports:
  #     - "3000:3000"

volumes:
  mysql-data:
    driver: local
