server:
  port: 8081
spring:
  application:
    name: user-service-fyb
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:3.113.113.164:8848}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ai_qa_system}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:ai_qa_system}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
security:
  jwt:
    secret: ${JWT_SECRET:changeme-in-prod}
    issuer: user-service-fyb
    expiration-minutes: 60
password:
  encoder:
    strength: 10